version: "3"
services:
  db:
    image: postgres:latest
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mynet


  sql-chain:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db  
    environment:  # Add your environment variables here
          DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
          OPENAI_API_KEY: your_key
    networks:
      - mynet


networks:
  mynet:
